on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Yocto environment
      run: |
         sudo apt-get install -y chrpath diffstat &
        # Set up Yocto environment here
          
    
    #- name: Setup Yocto environment
      #run: sudo locale-gen en_US.UTF-8
        # Set up Yocto environment here
        # source setup-yocto-env.sh

   # - name: Setup Yocto environment
    #  run: ./build.sh kernel
        # Set up Yocto environment here
        # source setup-yocto-env.sh

    - name: Build Yocto image
      run: ./build.sh yocto
      # bitbake core-image-minimal build
